### ISSUE TITLE
Crowdin Integration

### ISSUE THREAD

**Issue by ramvinvan** [Shardeum/shardeum-docs#11]

**Comment by MarcusWentz** [comment]
## Documentation

Docusaurus V2 guide for adding Crowdin language translations:

https://docusaurus.io/docs/i18n/crowdin

## Risk:

Crowdin not be fully automated yet for all languages 
(Docarsuarus V2 docs request support from this currently open issue):

https://github.com/facebook/docusaurus/issues/3526

**Comment by MarcusWentz** [comment]
We can open this after Mainnet, so that the Shardeum docs won't need to be updated as often then by translators.
