### ISSUE TITLE
Migrate and redirect docs.shardeum.org as shardeum.org/docs

### ISSUE THREAD

**Issue by ramvinvan** [Shardeum/shardeum-docs#12]

**Comment by MarcusWentz** [comment]
For now we could have 

https://shardeum.org/docs/ 

redirect to 

https://docs.shardeum.org/.

**Comment by MarcusWentz** [comment]
Running into an issue setting up the Shardeum Website locally to add this feature:

https://github.com/Shardeum/shardeum-website/issues/136

**Comment by MarcusWentz** [comment]
Trying to make the Shardeum Website setup more clear:

https://github.com/Shardeum/shardeum-website/pull/155

**Comment by MarcusWentz** [comment]
Closing and moving to 

https://github.com/Shardeum/shardeum-website/issues

**Comment by MarcusWentz** [comment]
Opened new issue here:

https://github.com/Shardeum/shardeum-website/issues/177
