### ISSUE TITLE
Validator Tutorial not displayed correctly in Blog

### ISSUE THREAD

**Issue by guilyx** [Shardeum/shardeum-docs#219]
Hey everyone.

https://github.com/Shardeum/shardeum-docs/blob/master/docs/node/run/validator.md

Here, the `docker-compose` installation line is correct in the markdown. 

https://shardeum.org/blog/how-to-run-a-validator-node-on-sphinx/

Here, it doesn't show entirely.

Thanks :-)

**Comment by MarcusWentz** [comment]
I am not able to modify the blog from this repository.

I will ask to see if we can update the blog.

**Comment by guilyx** [comment]
Yea wanted to throw in a PR but couldn't find this in here either :(
