### ISSUE TITLE
0|validator  | Error: Unacceptable config object shape, defective settings detected: server.ip.externalPort

### ISSUE THREAD

**Issue by bumkailashkumar** [Shardeum/shardeum-docs#224]
0|validator  | Error: Unacceptable config object shape, defective settings detected: server.ip.externalPort

pls explain how to fix this error when am trying toi start node from maintainenece tab from GUI

**Comment by MarcusWentz** [comment]
Please open a bug report here with a screenshot:

https://github.com/Shardeum/shardeum-bug-reporting
